### ISSUE TITLE
problem installing

### ISSUE THREAD

**Issue by plijnzaad** [gui11aume/HMMt#2]
I have trouble installing the package, both when using devtools install_github, and when doing it by first cloning followed by R CMD INSTALL. 

I get these error messages:

* installing *source* package ‘HMMt’ ...
fatal: Not a git repository (or any parent up to mount point /tmp)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
\nGit repository is dirty.
Commit or clean changes before install.\n
ERROR: configuration failed for package ‘HMMt’
* removing ‘/home/hub_kind/sperricone/R/x86_64-unknown-linux-gnu-library/3.1/HMMt’
Error: Command failed (1)

It appears to be caused by the configure script.

**Comment by gui11aume** [comment]
The purpose of the configure script is only to prevent you from installing a version of the package that does not correspond to a git commit (because then the version is untraceable). According to the error message, you did not clone the repo using git. The possible solutions are to erase the current repo and replace it with `git clone git@github.com:gui11aume/HMMt`, or just to erase the configure file (which does nothing else than preventing you from installing the package).

**Comment by gtrichard** [comment]
A reliable way to install the package in R is :
```
  system('git clone https://github.com/gui11aume/HMMt')
  system('rm HMMt/configure')
  library(devtools)
  # On Mac OS X if an error concerning gfortran is raised:
  # system('curl -O http://r.research.att.com/libs/gfortran-4.8.2-darwin13.tar.bz2')
  # system('sudo tar fvxj gfortran-4.8.2-darwin13.tar.bz2 -C /')
  devtools::install("HMMt/")
```

**Comment by gui11aume** [comment]
I have removed the configure and cleanup scripts. They belonged to another era where the software was still evolving and I needed to trace which version had been used to produce a given output. This stopped being useful and only caused frustration for the users.
